[package]
name = "hebo-ui-daemon"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"

[dependencies]
prost = "0.10.0"
tokio = { version = "1.17.0", features = ["rt-multi-thread"] }
tonic = "0.7.1"

[build-dependencies]
tonic-build = "0.7.0"
