[package]
name = "hebo-daemon"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.10.0"
tonic = "0.7.1"

[dev-dependencies]
tonic-build = "0.7.0"
