[package]
name = "hebo"
version = "0.1.0"
authors = ["Xu Shaohua <shaohua@biofan.org>"]
edition = "2018"
description = "Distributed MQTT broker"

[dependencies]
codec = { path = "codec" }

tokio = { version = "0.2.21", features = ["full"] }
log = "0.4.8"
env_logger = "0.7.1"
futures = "0.3.5"

[workspace]
members = [
	"codec",
	"ruo"
]
