version: "3.0"
services:
  mosquitto-ssl-ruo:
    image: eclipse-mosquitto:1.6.7
    restart: always
    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./ca:/mosquitto/ca:ro
      - ./data:/mosquitto/data

