
[general]
pid_file = "/tmp/hebo/mqtts-8883.pid"

[[listeners]]
address = "0.0.0.0:8883"
protocol = "mqtts"
cert_file = "./examples/certs/cert.pem"
key_file = "./examples/certs/key.pem"

[log]
log_file = "/tmp/hebo/hebo.log"
