[package]
name = "hebo"
version = "0.2.1"
authors = ["Xu Shaohua <shaohua@biofan.org>"]
edition = "2018"
license = "AGPL-3.0-only"
description = "Distributed MQTT broker"

[[bin]]
name = "hebo"
path = "src/bin/hebo.rs"

[[bin]]
name = "hebo-passwd"
path = "src/bin/hebo_passwd.rs"

[features]
default = []

full = [
  "allocator",
]
allocator = ["jemallocator"]
auth_redis = ["redis"]

[dependencies]
base64 = "0.13.0"
clap = "2.33.3"
codec = { path = "../codec" }
env_logger = "0.9.0"
futures = "0.3.16"
futures-util = "0.3.16"
http = "0.2.4"
jemallocator = { version = "0.3.2", optional = true }
log = "0.4.14"
log4rs = { version = "1.0.0", features = [ "background_rotation", "gzip" ] }
nc = "0.7.9"
openssl = "0.10.36"
quinn = "0.7.2"
rand = "0.8.4"
redis = { version = "0.21", optional = true }
serde = "1.0.129"
serde_derive = "1.0.129"
tokio = { version = "1.10.1", features = ["full"] }
tokio-rustls = "0.22.0"
tokio-tungstenite = { version = "0.15.0", features = ["rustls-tls"] }
toml = "0.5.8"
webpki-roots = "0.22.0"

[dev-dependencies]
rcgen = "0.8.13"
