[package]
name = "hebo"
version = "0.2.0"
authors = ["Xu Shaohua <shaohua@biofan.org>"]
edition = "2018"
license = "AGPL-3.0-only"
description = "Distributed MQTT broker"

[[bin]]
name = "hebo"
path = "src/bin/hebo.rs"

[dependencies]
codec = { path = "../codec" }
clap = "2.33.3"

env_logger = "0.8.3"
futures = "0.3.13"
log = "0.4.14"
serde = "1.0.124"
serde_derive = "1.0.124"
tokio = { version = "1.3.0", features = ["full"] }
toml = "0.5.8"
tokio-tungstenite = "0.14.0"
