[package]
name = "hebo"
version = "0.2.7"
authors = ["Xu Shaohua <shaohua@biofan.org>"]
description = "Distributed MQTT broker"
edition = "2021"
categories = [
  "concurrency",
  "network-programming",
]
keywords = [
  "broker",
  "hebo",
  "mqtt",
  "qos",
]
repository = "https://github.com/HeboProject/hebo"
homepage = "https://github.com/HeboProject/hebo"
license = "AGPL-3.0-only"
readme = "./README.md"
publish = true

[[bin]]
name = "hebo"
path = "src/bin/hebo.rs"

[features]
default = ["full"]

full = [
  "mongodb_conn",
  "mysql_conn",
  "pgsql_conn",
  "redis_conn",
]
mongodb_conn = ["mongodb"]
mysql_conn = ["mysql_async"]
pgsql_conn = ["tokio-postgres"]
redis_conn = ["redis"]

[dependencies]
base64 = "0.13.0"
chrono = { version = "0.4.19", features = ["serde"] }
clap = "3.1.18"
codec = { path = "../codec", package = "hebo_codec", version = "0.2.2" }
env_logger = "0.9.0"
futures = "0.3.21"
futures-util = "0.3.21"
http = "0.2.8"
jemallocator = { version = "0.5.0", optional = true }
log = "0.4.17"
log4rs = { version = "1.1.1", features = [ "background_rotation", "gzip" ] }
mongodb = { version = "2.2.2", optional = true }
mysql_async = { version = "0.30.0", optional = true }
nc = "0.8.3"
openssl = "0.10.40"
quinn = "0.8.3"
rand = "0.8.5"
redis = { version = "0.21.5", features = ["tokio-comp", "connection-manager"], optional = true }
rustls-pemfile = "1.0.0"
serde = { version = "1.0.137", features = ["derive"] }
tokio = { version = "1.19.2", features = ["full"] }
tokio-postgres = { version = "0.7.6", optional = true }
tokio-rustls = "0.23.4"
tokio-tungstenite = { version = "0.17.1", features = ["rustls"] }
toml = "0.5.9"
users = "0.11.0"
warp = "0.3.2"
webpki-roots = "0.22.3"

[dev-dependencies]
rcgen = "0.9.2"
ruo = { path = "../ruo", version = "0.1.2" }
tokio-test = "0.4.2"
