[package]
name = "hebo"
version = "0.1.0"
authors = ["Xu Shaohua <shaohua@biofan.org>"]
edition = "2018"
license = "AGPL-3.0-only"
description = "Distributed MQTT broker"

[[bin]]
name = "hebo"
path = "src/bin/hebo.rs"

[dependencies]
codec = { path = "../codec" }
clap = "2.33.3"

env_logger = "0.8.4"
futures = "0.3.15"
log = "0.4.14"
serde = "1.0.126"
serde_derive = "1.0.126"
tokio = { version = "1.7.1", features = ["full"] }
toml = "0.5.8"
