[general]
pid_file = "/tmp/hebo/mqtt-1883.pid"

[[listeners]]
address = "0.0.0.0:1883"
protocol = "mqtt"

[security]
allow_anonymous = false
password_file = "./examples/password.txt"

[log]
log_file = "/tmp/hebo/hebo.log"
