[package]
name = "ruo"
version = "0.1.0"
authors = ["Xu Shaohua <shaohua@biofan.org>"]
edition = "2018"

[dependencies]
codec = { path = "../codec" }

async-trait = "0.1.40"
byteorder = "1.3.4"
env_logger = "0.7.1"
futures = "0.3.5"
futures-util = "0.3.5"
log = "0.4.11"
native-tls = "0.2.4"
rustls = { version = "0.18.1", features = ["dangerous_configuration"] }
tokio = { version = "0.2.22", features = ["full"] }
tokio-tls = "0.3.1"
tokio-tungstenite = { version = "0.11.0", features = ["connect", "tls"] }
url = "2.1.1"
webpki = "0.21.3"
webpki-roots = "0.20.0"
