[package]
name = "ruo"
version = "0.1.0"
authors = ["Xu Shaohua <shaohua@biofan.org>"]
edition = "2018"

[dependencies]
codec = { path = "../codec" }

byteorder = "1.3.4"
tokio = { version = "0.2.17", features = ["full"] }
log = "0.4.8"
futures = "0.3.4"
async-trait = "0.1.30"
rustls = { version = "0.17.0", features = ["dangerous_configuration"] }
webpki-roots = "0.19.0"
env_logger = "0.7.1"
webpki = "0.21.2"
tokio-tls = "0.3.0"
native-tls = "0.2.4"
