[package]
name = "ruo"
version = "0.1.0"
authors = ["Xu Shaohua <shaohua@biofan.org>"]
description = "MQTT client library for Rust"
license = "Apache-2.0"
edition = "2021"
publish = true

[features]
default = ["blocking"]
blocking = []

[dependencies]
byteorder = "1.4.3"
codec = { path = "../codec", package = "hebo_codec", version = "0.1.2" }
env_logger = "0.9.0"
futures = "0.3.21"
futures-util = "0.3.21"
log = "0.4.17"
quinn = "0.8.2"
rustls-pemfile = "1.0.0"
tokio = { version = "1.18.1", features = ["full"] }
tokio-rustls = "0.23.4"
tokio-tungstenite = { version = "0.17.1", features = ["rustls-tls-webpki-roots"] }
url = "2.2.2"
webpki-roots = "0.22.3"
