[package]
name = "ruo"
version = "0.1.0"
authors = ["Xu Shaohua <shaohua@biofan.org>"]
edition = "2018"

[dependencies]
codec = { path = "../codec" }

byteorder = "1.4.3"
env_logger = "0.8.4"
futures = "0.3.15"
futures-util = "0.3.15"
log = "0.4.14"
native-tls = "0.2.7"
rustls = { version = "0.19.1", features = ["dangerous_configuration"] }
tokio = { version = "1.7.0", features = ["full"] }
tokio-tls = "0.3.1"
url = "2.2.2"
webpki = "0.22.0"
webpki-roots = "0.22.0"

[dev-dependencies]
protobuf = "2.24.1"

[build-dependencies]
protobuf-codegen-pure = "2.24.1"
