[package]
name = "ruo"
version = "0.1.0"
authors = ["Xu Shaohua <shaohua@biofan.org>"]
edition = "2018"

[dependencies]
codec = { path = "../codec" }

byteorder = "1.4.3"
env_logger = "0.8.3"
futures = "0.3.13"
futures-util = "0.3.13"
log = "0.4.14"
native-tls = "0.2.7"
rustls = { version = "0.19.0", features = ["dangerous_configuration"] }
tokio = { version = "1.4.0", features = ["full"] }
tokio-tls = "0.3.1"
tokio-tungstenite = { version = "0.14.0", features = ["connect", "tls"] }
url = "2.2.1"
webpki = "0.21.4"
webpki-roots = "0.21.0"

[dev-dependencies]
protobuf = "2.22.1"

[build-dependencies]
protobuf-codegen-pure = "2.22.1"
