[package]
name = "codec"
version = "0.1.0"
authors = ["Xu Shaohua <shaohua@biofan.org>"]
edition = "2018"
description = "Packet codec for MQTT protocol"

[dependencies]
byteorder = "1.4.3"
bytes = "1.1.0"
log = "0.4.14"
rand = "0.8.4"
serde = "1.0.130"
serde_derive = "1.0.130"
