version: "3.0"
services:
  redis:
    image: mongo:4.2
    restart: always
    ports:
      - 127.0.0.1:27017:27017
      - 127.0.0.1:27018:27018
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: hebo-mqtt
    volumes:
      - ./db:/data/db
