[metadata]
name = "hebo-ui"
app_id = "org.biofan.hebo"
author = "Xu Shaohua <shaohua@biofan.org"
description = "GUI tool for MQTT protocol"
homepage = "https://biofan.org"
version = "1.0.0"
license = "GPL-3.0"

workdir = "cmake-build-release/rs-builder"
src_dir = "cmake-build-release"

[linux]
targets = ["deb"]
arch = ["x86-64"]

files = [
	{from = "src/app/hebo-ui", to = "usr/bin/hebo-ui"},
	{from = "../pkg/hebo-ui.svg", to = "usr/share/icons/hicolor/scalable/apps/org.biofan.HeboUi.svg"},
	{from = "../pkg/hebo-ui.desktop", to = "usr/share/applications/org.biofan.HeboUi.desktop"},
]

[linux.deb]
depends = "libqt5core5a, libqt5svg5"
